name: Sync

on:
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  process:
    runs-on: ubuntu-latest
    environment:
      name: status

    steps:
    - name: Init Sequence
      uses: actions/checkout@v7

    - name: Gather Metrics
      id: state_eval
      run: |
        echo "c_dtl=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

    - name: Log State
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
          -f body="State synced. @${{ secrets.ADMIN }} - Ref: ${{ env.c_dtl }}"
